services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
    ports:
      - '5432:5432'
  node-backend:
    build: backend
    depends_on: [ postgres ]
    ports:
      - '3000:3000'
  frontend:
    build: frontend
    depends_on: [ node-backend ]
    ports:
      - '8080:80'
volumes:
  dbdata:

